spring:
  datasource:
    url: jdbc:mysql://finops-test-db.cddoiuqvzqdb.ap-northeast-2.rds.amazonaws.com:3306/finops_test_db?useSSL=false&serverTimezone=UTC
    username: testuser
    password: awsbackup133
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 2000
      max-lifetime: 30000
      minimum-idle: 10
      idle-timeout: 10000


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level:
  org.hibernate.SQL: debug
  com.zaxxer.hikari: debug

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"